version: "3.8"
services:
  www:
    container_name: "${CONTAINER_NAME_PHP}"
    build:
      context: ./apache_php
      dockerfile: Dockerfile
      args:
        php_version: "${VERSION_PHP}"
    ports:
      - "80:80"
    volumes:
      - ./www:/var/www/html
    links:
      - db_shop
      - db_login
    networks:
      - default
    depends_on:
      - db_shop
      - db_login

  db_shop:
    image: mysql:${VERSION_MYSQL}
    container_name: ${CONTAINER_NAME_MYSQL_SHOP}
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ${MYSQL_DB_SHOP}
      MYSQL_USER: ${MYSQL_USER_SHOP}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD_SHOP}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD_SHOP}
      TZ: ${TIMEZONE}
    volumes:
      - ./sql/sql_db_shop/:/docker-entrypoint-initdb.d
      - persistent_shop:/var/lib/mysql
    command:
      [
        "mysqld",
        "--default-authentication-plugin=mysql_native_password",
        "--character-set-server=utf8mb4",
        "--collation-server=utf8mb4_0900_as_cs",
      ]
    networks:
      - default
    restart: always

  db_login:
    image: mysql:${VERSION_MYSQL}
    container_name: ${CONTAINER_NAME_MYSQL_LOGIN}
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: ${MYSQL_DB_LOGIN}
      MYSQL_USER: ${MYSQL_USER_LOGIN}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD_LOGIN}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD_LOGIN}
      TZ: ${TIMEZONE}
    volumes:
      - ./sql/sql_db_login:/docker-entrypoint-initdb.d
      - persistent_login:/var/lib/mysql
    command:
      [
        "mysqld",
        "--default-authentication-plugin=mysql_native_password",
        "--character-set-server=utf8mb4",
        "--collation-server=utf8mb4_0900_as_cs",
      ]
    networks:
      - default
    restart: always

  phpmyadmin_login:
    container_name: ${CONTAINER_NAME_PMA_LOGIN}
    image: phpmyadmin/phpmyadmin
    links:
      - db_login:db
    ports:
      - 8081:80
  phpmyadmin_shop:
    container_name: ${CONTAINER_NAME_PMA_SHOP}
    image: phpmyadmin/phpmyadmin
    links:
      - db_shop:db
    ports:
      - 8080:80

volumes:
  persistent_shop:
  persistent_login:
