version: "3.8"
services:
    www:
        container_name: "${NAME_PHP}"
        build:
            context: .
            dockerfile: Dockerfile
            args:
                php_version: "${VERSION_PHP}"
        ports:
            - "80:80"
        volumes:
            - ./www:/var/www/html
        links:
            - db_shop
        networks:
            - default
        depends_on:
            - db_shop

    db_shop:
        image: mysql:5.7.30
        container_name: ${NAME_MYSQL_SHOP}
        ports:
            - "3308:3306"
        environment:
            MYSQL_DATABASE: ${MYSQL_DATABASE_SHOP}
            MYSQL_USER: ${MYSQL_USER_SHOP}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD_SHOP}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD_SHOP}
        volumes:
            - persistent:/var/lib/mysql
        networks:
            - default
        restart: always

    phpmyadmin_shop:
        container_name: ${NAME_PMA_SHOP}
        image: phpmyadmin/phpmyadmin
        links:
            - db_shop:db
        ports:
            - 1234:80
volumes:
    persistent:
